-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "totalPrice" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "amenities" TEXT,
ADD COLUMN     "bathrooms" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "floor" INTEGER,
ADD COLUMN     "price12h" DOUBLE PRECISION,
ADD COLUMN     "price24h" DOUBLE PRECISION,
ADD COLUMN     "price6h" DOUBLE PRECISION,
ADD COLUMN     "pricePerDay" DOUBLE PRECISION,
ADD COLUMN     "rooms" INTEGER NOT NULL DEFAULT 1;
